name: Minify CSS and Js
on:
  push:
  workflow_dispatch:
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: publish

