name: Minify CSS and Js

on:
  push:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true

      - name: Fetch remote changes
        run: git fetch origin publish

      - name: Switch to publish branch
        run: git checkout publish

      - name: Merge changes from origin/publish
        run: git merge origin/publish

      - name: Resolve merge conflicts if any
        run: git merge --continue || true

      - name: Switch back to main branch
        run: git checkout main

      - name: Merge changes from publish branch
        run: git merge --strategy-option=theirs publish

      - name: Push changes to publish branch (force overwrite)
        run: git push --force origin publish
