      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .

          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Minify Code"
            git push origin HEAD:publish
          fi
