name: Minify CSS and Js
on:
  push:
  workflow_dispatch:
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Minifing Code"
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git pull -f origin publish --rebase
            git checkout publish
            git add .
            git commit -m "Minify Code"
            git push -f
          fi
