name: Convert Events to JSON
on:
  push:
    paths:
      - 'events.md'
      - 'convert.js'
  # allows to manually run the job at any time
  workflow_dispatch:
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run script
        run: node ./convert.js
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add events.json
          if git diff --staged --quiet; then
            echo "No changes in events.json"
          else
            git commit -m "Update events.json"
            git push
          fi
