name: Minify CSS and Js

on:
  push:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Main to Publish
        run: |
          git checkout -b publish
          git fetch origin main:publish
          git checkout publish
          git push origin publish -f
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Minify Code"
            git pull origin publish --rebase
            git push origin HEAD:publish
          fi
