name: Copy to Publish Branch

on:
  push:
    branches:
      - main

jobs:
  copy-to-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Publish Branch
        run: git checkout -b publish

      - name: Copy Files
        run: |
          cp -r * .
          git add -A
          git commit -m "Copy files to publish branch"
          git push origin publish
