name: Minify CSS and Js
on:
  push:
  workflow_dispatch:
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          overwrite: true
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .

          if git diff --staged --quiet; then
            echo "No changes"
          else
            git commit -m "Minify Code"
            git push origin HEAD:publish
          fi
